// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai/assistant-profiles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/assistant-profiles">> = Specific
  const handler = {} as typeof import("../../app/ai/assistant-profiles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai/assistant/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/assistant/sessions">> = Specific
  const handler = {} as typeof import("../../app/ai/assistant/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai/cost/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/cost">> = Specific
  const handler = {} as typeof import("../../app/ai/cost/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/messages">> = Specific
  const handler = {} as typeof import("../../app/ai/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai/redline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/redline">> = Specific
  const handler = {} as typeof import("../../app/ai/redline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-log">> = Specific
  const handler = {} as typeof import("../../app/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broadcasts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts/[id]">> = Specific
  const handler = {} as typeof import("../../app/broadcasts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broadcasts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts/new">> = Specific
  const handler = {} as typeof import("../../app/broadcasts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broadcasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts">> = Specific
  const handler = {} as typeof import("../../app/broadcasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/flags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flags">> = Specific
  const handler = {} as typeof import("../../app/flags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/matching-health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matching-health">> = Specific
  const handler = {} as typeof import("../../app/matching-health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/risk">> = Specific
  const handler = {} as typeof import("../../app/risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roles">> = Specific
  const handler = {} as typeof import("../../app/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search/analytics">> = Specific
  const handler = {} as typeof import("../../app/search/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search/categories">> = Specific
  const handler = {} as typeof import("../../app/search/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/keywords/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search/keywords">> = Specific
  const handler = {} as typeof import("../../app/search/keywords/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tickets">> = Specific
  const handler = {} as typeof import("../../app/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/users/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/users/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/users/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/customers">> = Specific
  const handler = {} as typeof import("../../app/users/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../app/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/users/therapists/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/therapists/[id]">> = Specific
  const handler = {} as typeof import("../../app/users/therapists/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/users/therapists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/therapists">> = Specific
  const handler = {} as typeof import("../../app/users/therapists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verifications">> = Specific
  const handler = {} as typeof import("../../app/verifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/withdrawals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/withdrawals">> = Specific
  const handler = {} as typeof import("../../app/withdrawals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
